	nios_system u0 (
		.audio_ADCDAT               (<connected-to-audio_ADCDAT>),               //                audio.ADCDAT
		.audio_ADCLRCK              (<connected-to-audio_ADCLRCK>),              //                     .ADCLRCK
		.audio_BCLK                 (<connected-to-audio_BCLK>),                 //                     .BCLK
		.audio_DACDAT               (<connected-to-audio_DACDAT>),               //                     .DACDAT
		.audio_DACLRCK              (<connected-to-audio_DACLRCK>),              //                     .DACLRCK
		.audio_clk_clk              (<connected-to-audio_clk_clk>),              //            audio_clk.clk
		.audio_pll_ref_clk_clk      (<connected-to-audio_pll_ref_clk_clk>),      //    audio_pll_ref_clk.clk
		.audio_pll_ref_reset_reset  (<connected-to-audio_pll_ref_reset_reset>),  //  audio_pll_ref_reset.reset
		.av_config_SDAT             (<connected-to-av_config_SDAT>),             //            av_config.SDAT
		.av_config_SCLK             (<connected-to-av_config_SCLK>),             //                     .SCLK
		.expansion_jp5_export       (<connected-to-expansion_jp5_export>),       //        expansion_jp5.export
		.flash_ADDR                 (<connected-to-flash_ADDR>),                 //                flash.ADDR
		.flash_CE_N                 (<connected-to-flash_CE_N>),                 //                     .CE_N
		.flash_OE_N                 (<connected-to-flash_OE_N>),                 //                     .OE_N
		.flash_WE_N                 (<connected-to-flash_WE_N>),                 //                     .WE_N
		.flash_RST_N                (<connected-to-flash_RST_N>),                //                     .RST_N
		.flash_DQ                   (<connected-to-flash_DQ>),                   //                     .DQ
		.green_leds_export          (<connected-to-green_leds_export>),          //           green_leds.export
		.pushbuttons_export         (<connected-to-pushbuttons_export>),         //          pushbuttons.export
		.red_leds_export            (<connected-to-red_leds_export>),            //             red_leds.export
		.sd_card_b_SD_cmd           (<connected-to-sd_card_b_SD_cmd>),           //              sd_card.b_SD_cmd
		.sd_card_b_SD_dat           (<connected-to-sd_card_b_SD_dat>),           //                     .b_SD_dat
		.sd_card_b_SD_dat3          (<connected-to-sd_card_b_SD_dat3>),          //                     .b_SD_dat3
		.sd_card_o_SD_clock         (<connected-to-sd_card_o_SD_clock>),         //                     .o_SD_clock
		.sdram_addr                 (<connected-to-sdram_addr>),                 //                sdram.addr
		.sdram_ba                   (<connected-to-sdram_ba>),                   //                     .ba
		.sdram_cas_n                (<connected-to-sdram_cas_n>),                //                     .cas_n
		.sdram_cke                  (<connected-to-sdram_cke>),                  //                     .cke
		.sdram_cs_n                 (<connected-to-sdram_cs_n>),                 //                     .cs_n
		.sdram_dq                   (<connected-to-sdram_dq>),                   //                     .dq
		.sdram_dqm                  (<connected-to-sdram_dqm>),                  //                     .dqm
		.sdram_ras_n                (<connected-to-sdram_ras_n>),                //                     .ras_n
		.sdram_we_n                 (<connected-to-sdram_we_n>),                 //                     .we_n
		.sdram_clk_clk              (<connected-to-sdram_clk_clk>),              //            sdram_clk.clk
		.serial_port_RXD            (<connected-to-serial_port_RXD>),            //          serial_port.RXD
		.serial_port_TXD            (<connected-to-serial_port_TXD>),            //                     .TXD
		.slider_switches_export     (<connected-to-slider_switches_export>),     //      slider_switches.export
		.sram_DQ                    (<connected-to-sram_DQ>),                    //                 sram.DQ
		.sram_ADDR                  (<connected-to-sram_ADDR>),                  //                     .ADDR
		.sram_LB_N                  (<connected-to-sram_LB_N>),                  //                     .LB_N
		.sram_UB_N                  (<connected-to-sram_UB_N>),                  //                     .UB_N
		.sram_CE_N                  (<connected-to-sram_CE_N>),                  //                     .CE_N
		.sram_OE_N                  (<connected-to-sram_OE_N>),                  //                     .OE_N
		.sram_WE_N                  (<connected-to-sram_WE_N>),                  //                     .WE_N
		.system_pll_ref_clk_clk     (<connected-to-system_pll_ref_clk_clk>),     //   system_pll_ref_clk.clk
		.system_pll_ref_reset_reset (<connected-to-system_pll_ref_reset_reset>), // system_pll_ref_reset.reset
		.video_in_PIXEL_CLK         (<connected-to-video_in_PIXEL_CLK>),         //             video_in.PIXEL_CLK
		.video_in_LINE_VALID        (<connected-to-video_in_LINE_VALID>),        //                     .LINE_VALID
		.video_in_FRAME_VALID       (<connected-to-video_in_FRAME_VALID>),       //                     .FRAME_VALID
		.video_in_pixel_clk_reset   (<connected-to-video_in_pixel_clk_reset>),   //                     .pixel_clk_reset
		.video_in_PIXEL_DATA        (<connected-to-video_in_PIXEL_DATA>)         //                     .PIXEL_DATA
	);

