	nios_system2 u0 (
		.audio_ADCDAT              (<connected-to-audio_ADCDAT>),              //               audio.ADCDAT
		.audio_ADCLRCK             (<connected-to-audio_ADCLRCK>),             //                    .ADCLRCK
		.audio_BCLK                (<connected-to-audio_BCLK>),                //                    .BCLK
		.audio_DACDAT              (<connected-to-audio_DACDAT>),              //                    .DACDAT
		.audio_DACLRCK             (<connected-to-audio_DACLRCK>),             //                    .DACLRCK
		.audio_clk_clk             (<connected-to-audio_clk_clk>),             //           audio_clk.clk
		.audio_irq_irq             (<connected-to-audio_irq_irq>),             //           audio_irq.irq
		.audio_pll_ref_clk_clk     (<connected-to-audio_pll_ref_clk_clk>),     //   audio_pll_ref_clk.clk
		.audio_pll_ref_reset_reset (<connected-to-audio_pll_ref_reset_reset>), // audio_pll_ref_reset.reset
		.audio_reset_reset         (<connected-to-audio_reset_reset>),         //         audio_reset.reset
		.audio_slave_address       (<connected-to-audio_slave_address>),       //         audio_slave.address
		.audio_slave_chipselect    (<connected-to-audio_slave_chipselect>),    //                    .chipselect
		.audio_slave_read          (<connected-to-audio_slave_read>),          //                    .read
		.audio_slave_write         (<connected-to-audio_slave_write>),         //                    .write
		.audio_slave_writedata     (<connected-to-audio_slave_writedata>),     //                    .writedata
		.audio_slave_readdata      (<connected-to-audio_slave_readdata>),      //                    .readdata
		.av_config_SDAT            (<connected-to-av_config_SDAT>),            //           av_config.SDAT
		.av_config_SCLK            (<connected-to-av_config_SCLK>),            //                    .SCLK
		.clk_clk                   (<connected-to-clk_clk>),                   //                 clk.clk
		.expansion_jp5_export      (<connected-to-expansion_jp5_export>),      //       expansion_jp5.export
		.flash_ADDR                (<connected-to-flash_ADDR>),                //               flash.ADDR
		.flash_CE_N                (<connected-to-flash_CE_N>),                //                    .CE_N
		.flash_OE_N                (<connected-to-flash_OE_N>),                //                    .OE_N
		.flash_WE_N                (<connected-to-flash_WE_N>),                //                    .WE_N
		.flash_RST_N               (<connected-to-flash_RST_N>),               //                    .RST_N
		.flash_DQ                  (<connected-to-flash_DQ>),                  //                    .DQ
		.green_leds_export         (<connected-to-green_leds_export>),         //          green_leds.export
		.pushbuttons_export        (<connected-to-pushbuttons_export>),        //         pushbuttons.export
		.red_leds_export           (<connected-to-red_leds_export>),           //            red_leds.export
		.reset_reset_n             (<connected-to-reset_reset_n>),             //               reset.reset_n
		.sdram_addr                (<connected-to-sdram_addr>),                //               sdram.addr
		.sdram_ba                  (<connected-to-sdram_ba>),                  //                    .ba
		.sdram_cas_n               (<connected-to-sdram_cas_n>),               //                    .cas_n
		.sdram_cke                 (<connected-to-sdram_cke>),                 //                    .cke
		.sdram_cs_n                (<connected-to-sdram_cs_n>),                //                    .cs_n
		.sdram_dq                  (<connected-to-sdram_dq>),                  //                    .dq
		.sdram_dqm                 (<connected-to-sdram_dqm>),                 //                    .dqm
		.sdram_ras_n               (<connected-to-sdram_ras_n>),               //                    .ras_n
		.sdram_we_n                (<connected-to-sdram_we_n>),                //                    .we_n
		.serial_port_RXD           (<connected-to-serial_port_RXD>),           //         serial_port.RXD
		.serial_port_TXD           (<connected-to-serial_port_TXD>),           //                    .TXD
		.slider_switches_export    (<connected-to-slider_switches_export>),    //     slider_switches.export
		.sram_DQ                   (<connected-to-sram_DQ>),                   //                sram.DQ
		.sram_ADDR                 (<connected-to-sram_ADDR>),                 //                    .ADDR
		.sram_LB_N                 (<connected-to-sram_LB_N>),                 //                    .LB_N
		.sram_UB_N                 (<connected-to-sram_UB_N>),                 //                    .UB_N
		.sram_CE_N                 (<connected-to-sram_CE_N>),                 //                    .CE_N
		.sram_OE_N                 (<connected-to-sram_OE_N>),                 //                    .OE_N
		.sram_WE_N                 (<connected-to-sram_WE_N>),                 //                    .WE_N
		.video_ext_PIXEL_CLK       (<connected-to-video_ext_PIXEL_CLK>),       //           video_ext.PIXEL_CLK
		.video_ext_LINE_VALID      (<connected-to-video_ext_LINE_VALID>),      //                    .LINE_VALID
		.video_ext_FRAME_VALID     (<connected-to-video_ext_FRAME_VALID>),     //                    .FRAME_VALID
		.video_ext_pixel_clk_reset (<connected-to-video_ext_pixel_clk_reset>), //                    .pixel_clk_reset
		.video_ext_PIXEL_DATA      (<connected-to-video_ext_PIXEL_DATA>)       //                    .PIXEL_DATA
	);

